### ISSUE TITLE
Issues with v2.1 data

### ISSUE THREAD

**Issue by psavoy** [mikejohnson51/nwmTools#4]
I have been digging into the NWM data over the past few days and I think there may be some issues with the v2.1 data. At first I thought perhaps that it was somehow a units issue, but after poking around more there does not seem to be a consistent bias across all sites that would indicate a units problem.

I attached 3 plots (grey dots are NWIS, orange line is NWM 2.1 and the other lines are NWM v1.2 and v2) that show three different behaviors of the v2.1 data: 1.) no variation, 2.) consistent underestimation, and 3.) consistent overestimation. These were just pulled using readNWMdata and aggregated to daily means for easier plotting. I'm happy to provide follow up or examples or help as I can.

![1-no variation](https://user-images.githubusercontent.com/30932979/160658496-b143cd8b-cc54-4daf-8d54-7153d252b87d.png)

![2- little variation](https://user-images.githubusercontent.com/30932979/160658512-f10daabd-f15f-4587-841b-452542bd4e15.png)

![3- high bias](https://user-images.githubusercontent.com/30932979/160658529-950b91ca-0259-4838-bf33-54020459ea16.png)

**Comment by mikejohnson51** [comment]
Hi @psavoy,

Thanks - you did find an error in my assumptions!! I have updated the index table and will push it shortly to close this issue but for now things are looking aligned (locally) with your example sites:

``` r
library(ggplot2)
library(nwmTools)

# Reusable plotting function

plot_data = function(data, ID = NULL) {
  ggplot(data = data) + 
    geom_line(aes(x = dateTime, y = flow_cms_v1.2, color = "v1.2")) + 
    geom_line(aes(x = dateTime, y = flow_cms_v2,   color = "v2.0")) +
    geom_line(aes(x = dateTime, y = flow_cms_v2.1, color = "v2.1")) +
    geom_line(aes(x = dateTime, y = flow_cms_nwis, color = "nwis")) +
    labs(y = 'Flows', x = "DateTime", title = paste0(
      "Model Comparison vs Observation: NWIS-", ID), 
      color ="Model") + 
    theme_bw() +
    theme(legend.position = "bottom")
}


data = readNWMdata(siteID = '01017000', 
            startDate = "2015-01-01",
            endDate = "2016-01-01",
            version = c(1.2, 2.0, 2.1),
            addObs = TRUE)

plot_data(data, data$siteID[1])
```

![](https://i.imgur.com/Z78Gyzx.png)

``` r
data = readNWMdata(siteID = '01017290', 
                   startDate = "2015-01-01",
                   endDate = "2016-01-01",
                   version = c(1.2, 2.0, 2.1),
                   addObs = TRUE)

plot_data(data, data$siteID[1])
```

![](https://i.imgur.com/nKQmOUG.png)

``` r
data = readNWMdata(siteID = '01073785', 
                   startDate = "2015-01-01",
                   endDate = "2016-01-01",
                   version = c(1.2, 2.0, 2.1),
                   addObs = TRUE)

plot_data(data, data$siteID[1])
```

![](https://i.imgur.com/UU4a5c9.png)


<sup>Created on 2022-03-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

We did find that 42 seemingly random hours are missing from the NWM record (see #3) these are being addressed and will be undated soon as well.

Thanks for working through the issue and please let me know what else you find,

Mike
